#!/usr/bin/env python3
"""Import SmartBugs-Curated labels for the implementation-layer classes.

Why this exists
---------------
V9 and V10 (code defect, broken accounting invariant) are real classes with
strong published evidence, but the stablecoin corpus contains no hand-verified
instance of either. Rather than self-assign labels — which would let the
project grade its own homework — this imports externally-provided ground truth
from SmartBugs-Curated (143 contracts, 208 tagged vulnerabilities, Apache-2.0).

Run after:  asv corpus --benchmarks && asv slice

Line -> function resolution
---------------------------
SmartBugs labels a LINE; this project matches on a FUNCTION. Each label's line
is therefore resolved to the enclosing sliced function. Labels whose line falls
outside any function body (contract-level state variables, pragmas) cannot be
matched by construction and are dropped, with the count reported — silently
keeping them would inflate the false-negative count with cases the slicer was
never able to see.

Writes labels/smartbugs.yaml. This is a SEPARATE track: `asv evaluate` reads
ground_truth.yaml by default and only reads this file when asked, via
`asv evaluate --labels smartbugs.yaml --protocol-track benchmark`.

Annotation leak
---------------
SmartBugs writes its ground truth into the source: the vulnerable line carries
`// <yes> <report> ACCESS_CONTROL` and the header carries
`@vulnerable_at_lines: 31,38`. Before the guard in `slicing._mk_slice`, 153 of
826 benchmark slices still carried an annotation and 181 of these 196 labels
sat on one — the model could have read the answer from a comment. Benchmark
slices are now comment-stripped (line counts preserved, so the line -> function
resolution below is unaffected). Do not remove that guard and then trust these
numbers.
"""
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from asv.config import Config  # noqa: E402

BENCH = "smartbugs-curated"

# DASP category -> our class. Only categories with a defensible mapping are
# imported; anything else is skipped rather than forced into a class.
CATEGORY_MAP = {
    "reentrancy": "V9",
    "access_control": "V4",
    "arithmetic": "V10",
    "unchecked_low_level_calls": "V9",
    "denial_of_service": "V9",
    "bad_randomness": "V10",
    "front_running": "V7",
    "time_manipulation": "V7",
    "short_addresses": "V9",
}


def main() -> int:
    cfg = Config.load()
    root = cfg.path("raw") / "_benchmarks" / BENCH
    vfile = root / "vulnerabilities.json"
    if not vfile.exists():
        print(f"not found: {vfile}\nRun `asv corpus --benchmarks` first.",
              file=sys.stderr)
        return 1

    slices_path = cfg.path("processed") / "slices.json"
    if not slices_path.exists():
        print("slices.json missing — run `asv corpus --benchmarks` then "
              "`asv slice` first.", file=sys.stderr)
        return 1

    # file -> [(start, end, function)] for the benchmark protocol only
    spans: dict[str, list[tuple[int, int, str]]] = {}
    for s in json.loads(slices_path.read_text("utf-8")):
        if s.get("protocol") != BENCH:
            continue
        spans.setdefault(s["file"].replace("\\", "/"), []).append(
            (int(s["start_line"]), int(s["end_line"]), s["function"]))

    if not spans:
        print(f"no sliced functions found for protocol '{BENCH}'.\n"
              "Run `asv corpus --benchmarks` (which now collects the "
              "benchmark sources) and then `asv slice`.", file=sys.stderr)
        return 1

    def enclosing(path: str, line: int) -> str | None:
        for start, end, fn in spans.get(path, []):
            if start <= line <= end:
                return fn
        return None

    data = json.loads(vfile.read_text("utf-8"))
    out = ["# Auto-generated by scripts/import_smartbugs.py. Do not edit by hand.",
           "# Source: https://github.com/smartbugs/smartbugs-curated (Apache-2.0)",
           "#",
           "# External ground truth for the implementation-layer classes. Kept in a",
           "# separate file from labels/ground_truth.yaml so that this benchmark",
           "# never contaminates the headline stablecoin metrics.",
           "labels:"]

    kept: Counter = Counter()
    unresolved = 0
    unmapped = 0
    for entry in data:
        path = (entry.get("path") or "").replace("\\", "/")
        for v in entry.get("vulnerabilities", []):
            cat = v.get("category", "")
            vid = CATEGORY_MAP.get(cat)
            if not vid:
                unmapped += 1
                continue
            lines = v.get("lines") or []
            fn = None
            for ln in lines:
                fn = enclosing(path, int(ln))
                if fn:
                    break
            if not fn:
                unresolved += 1
                continue
            kept[vid] += 1
            out += [f"  - protocol: {BENCH}",
                    f"    file_contains: {path}",
                    f"    function: {fn}",
                    f"    vuln_id: {vid}",
                    f"    source: smartbugs-curated:{cat}",
                    f"    note: \"line {lines[0] if lines else '?'} -> {fn}()\""]

    dest = cfg.root / "labels" / "smartbugs.yaml"
    dest.write_text("\n".join(out) + "\n", "utf-8")
    total = sum(kept.values())
    print(f"wrote {total} benchmark labels to {dest}")
    print(f"  by class : {dict(sorted(kept.items()))}")
    print(f"  dropped  : {unresolved} (line not inside any sliced function), "
          f"{unmapped} (category not mapped)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
